INSERT INTO skills (name, created_by) VALUES
-- IT Skills
('Java', 'administrator'),
('Python', 'administrator'),
('JavaScript', 'administrator'),
('C++', 'administrator'),
('C#', 'administrator'),
('PHP', 'administrator'),
('Ruby', 'administrator'),
('Go', 'administrator'),
('Swift', 'administrator'),
('Kotlin', 'administrator'),
('HTML', 'administrator'),
('CSS', 'administrator'),
('React.js', 'administrator'),
('Angular', 'administrator'),
('Vue.js', 'administrator'),
('Node.js', 'administrator'),
('SQL', 'administrator'),
('MySQL', 'administrator'),
('PostgreSQL', 'administrator'),
('MongoDB', 'administrator'),
('Oracle', 'administrator'),
('Redis', 'administrator'),
('Docker', 'administrator'),
('Kubernetes', 'administrator'),
('Jenkins', 'administrator'),
('CI/CD Pipelines', 'administrator'),
('AWS', 'administrator'),
('Azure', 'administrator'),
('Google Cloud Platform', 'administrator'),
('R', 'administrator'),
('MATLAB', 'administrator'),
('TensorFlow', 'administrator'),
('Pandas', 'administrator'),
('NumPy', 'administrator'),
('Apache Spark', 'administrator'),
('Power BI', 'administrator'),
('Tableau', 'administrator'),
('Ethical Hacking', 'administrator'),
('Penetration Testing', 'administrator'),
('Network Security', 'administrator'),
('ISO 27001', 'administrator'),
('Firewalls', 'administrator'),
('Encryption', 'administrator'),
('Android Development', 'administrator'),
('iOS Development', 'administrator'),
('React Native', 'administrator'),
('Flutter', 'administrator'),
('Unity', 'administrator'),
('Unreal Engine', 'administrator'),
('Game Design', 'administrator'),
('3D Modeling', 'administrator'),

-- Business Skills
('Agile', 'administrator'),
('Scrum', 'administrator'),
('Kanban', 'administrator'),
('Waterfall Methodology', 'administrator'),
('Stakeholder Management', 'administrator'),
('SEO', 'administrator'),
('SEM', 'administrator'),
('Social Media Marketing', 'administrator'),
('Content Creation', 'administrator'),
('Email Marketing', 'administrator'),
('Google Analytics', 'administrator'),
('Financial Analysis', 'administrator'),
('Budgeting', 'administrator'),
('Forecasting', 'administrator'),
('Accounting Principles', 'administrator'),
('QuickBooks', 'administrator'),
('Recruitment', 'administrator'),
('Onboarding', 'administrator'),
('Training & Development', 'administrator'),
('Employee Relations', 'administrator'),

-- Engineering Skills
('Circuit Design', 'administrator'),
('PCB Design', 'administrator'),
('IoT', 'administrator'),
('CAD', 'administrator'),
('CAM', 'administrator'),
('Thermodynamics', 'administrator'),
('FEA', 'administrator'),
('Structural Analysis', 'administrator'),
('GIS', 'administrator'),
('Surveying', 'administrator'),
('Construction Management', 'administrator'),

-- Design Skills
('Adobe Photoshop', 'administrator'),
('Adobe Illustrator', 'administrator'),
('Figma', 'administrator'),
('Sketch', 'administrator'),
('UX/UI Design', 'administrator'),
('Video Editing', 'administrator'),
('Animation', 'administrator'),
('3D Rendering', 'administrator');
